config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about', to: 'homes#about', as: 'about'
  resources :books, only: [:new, :index, :show, :create, :edit, :destroy, :update]
  resources :users, only: [:show, :edit, :update, :index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books,dependent: :destroy
  has_one_attached :profile_image
  validates :name, presence: true
  validates :name, length: { in: 2..20 }
  validates :name, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top]
  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    '/'
  end

  def destroy
    redirect_to about_path

  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @books = Book.all
    @user = current_user
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      render :index
    end
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @users = User.all
  end

  def edit
    @book = Book.find(params[:id])
    @user = current_user
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    if @book.save
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @user = User.all
  end

  def about

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @users = User.all
    @user = current_user
    @book = Book.all
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    is_matching_login_user
    @user = User.find(params[:id])
  end

  def update
    is_matching_login_user
    @user = User.find(params[:id])
    @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to current_user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div id="error_explanation">
    <% if @book.errors.any? %>
      <h3><%= @book.errors.count %>error prohibited this obj from being saved</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= form_with model: @book do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, autofocus: true, id: "book_title", class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <label for ="book_opinion">Opinion</label>
          <%= f.text_field :body, autofocus: true, id: "book_body", class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book' %>
        </div>
      <% end %>
      <%= link_to 'Show', book_path, class: 'book_123215' %>
      |
      <%= link_to 'Back', books_path, class: 'back' %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<%= flash[:notice] %>


<div class="container px-5 px-sm-0">
  <div class="error_explanation">
    <% if @book.errors.any? %>
      <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="row">
    <%= render 'users/list', user: @user,book: @book %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Option</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= image_tag book.user.get_profile_image(100,100) %>
              </td>
              <td>
                <%= link_to book.title, book_path(book) %>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<%= flash[:notice] %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/list', user: @user, book: Book.new %>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= image_tag @user.get_profile_image(100,100) %>

              <%= link_to @user.name, user_path(@user) %>
            </td>
            <td>
              <%= link_to @book.title, book_path(@book) %>
            </td>
            <td>
              <%= @book.body %>
            </td>
            <td>
              <% if @user == current_user %>
                <%= link_to 'Edit', edit_book_path %>
              <%end %>
            </td>
            <td>
              <% if @user == current_user %>
                <%= link_to 'Destroy', book_path, method: :delete %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<main>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">
        Welcome to <i class="fa-solid fa-book"></i></i> <strong>Bookers!</strong>
      </h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<%= flash[:notice] %>
<main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>Welcome to <i class="fa-solid fa-book"></i></i> <strong>Bookers</strong></h1>
        <p>In<i class="fa-solid fa-book"></i><strong>Bookers</strong></p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>

        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to 'Log in', new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3"%>
          </div>
          <div class="row">
            <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-success btn-sm btn-block mb-5"%>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/4252c4d753.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to root_path, class: "navbar-brand p-3", method: :get do %>
            <span>Bookers</span>
          <% end %>
          <button class="navbar-toggler">
            <span class="navbar-toggler-icon"></span>
          </button>
          <% if user_signed_in? %>
            <div class="navbar-collapse collapse show" id="navbarNavDropdown" style>
              <ul class="navbar-nav ml-auto">
                <li>
                  <%= link_to user_path(current_user), class: "nav-link text-light", method: :get do %>
                    <i class="fa-solid fa-home"></i> Home
                  <% end %>
        　       </li>
                <li>
                  <%= link_to users_path, class: "nav-link text-light", method: :get do %>
                    <i class="fa-solid fa-users"></i> Users
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path, class: "nav-link text-light", method: :get do %>
                    <i class="fa-solid fa-book-open"></i> Books
                  <% end %>
                </li>
                <li>
                  <%= link_to  destroy_user_session_path, class: "nav-link text-light", method: :delete do %>
                    <i class="fa-solid fa-sign-out-alt"></i> Log out
                  <% end %>
                </li>
          <% else %>
                <li>
                  <%= link_to root_path, class: "nav-link text-light", method: :get do %>
                    <i class="fa-solid fa-home"></i> Home
                  <% end %>
                </li>
                <li>
                  <%= link_to about_path, class: "nav-link text-light", method: :get do %>
                    <i class="fa-solid fa-link"></i> About
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class: "nav-link text-light", method: :get do %>
                    <i class="fa-solid fa-user-plus"></i> Sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class: "nav-link text-light", method: :get do %>
                    <i class="fa-solid fa-right-to-bracket"></i> Log in
                  <% end %>
                </li>
              </ul>
            </div>
          <% end %>
        </div>
      </nav>
    </header>

    <%= yield %>

    <footer>
      <divclass="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_list.html.erb
    <div class="col-md-3">
      <h2>User info</h2>
      <table class="table">
      <th><%= image_tag user.get_profile_image(100,100) %></th>
        <tbody>
            <tr>
              <th><p>name</p></th>
              <th><%= user.name %></th>
            </tr>
            <tr>
              <th><p>introduction</p></th>
              <th><%= user.introduction %></th>
            </tr>
        </tbody>
      </table>

      <div class="row">
        <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block edit_user_158517",method: :get do %>
           <i class="fa-solid fa-user-gear"></i>
        <% end %>
      </div>

      <h2 class="mt-3">New book</h2>
      <%= form_with model: book, url: books_path, method: :post do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
        </div>
        <%= f.text_field :title %>
        <div class="form-group">
          <label for="book_opinion">Option</label>
        </div>
        <%= f.text_area :body %>

  　　　　　<%= f.submit 'Create Book' %>

      <% end %>
    </div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
        <h2><%= @user.errors.count %>error prohibited this obj from being saved:</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <label for="inputName">Name</label>
          <%= f.text_field :name, autofocus: true, id: "inputName", class: "form-control" %>
        </div>
        <div class="form-group">
          <label for="inputImage">Image</label>
          <%= f.file_field :profile_image,  accept: "image/*", class: "form-control-file user_image" %>
        </div>
        <div class="form-group">
          <label for="introduction">isntroduction</label>
          <%= f.text_area :introduction, id: "inputIntroduction", class: "form-control introduction" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update User' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/list', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= image_tag user.get_profile_image(100,100) %>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>
                <%= link_to 'Show', user_path(user) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= flash[:notice] %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/list', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Option</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= image_tag @user.get_profile_image(100,100) %>
              </td>
              <td>
                <%= link_to book.title, book_path(book) %>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>